config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :jobs, only: %i[index show]
  resources :feedback_uploads, only: %i[new create]
  resources :mailboxes
  resources :domains, only: %i[index show] do
    resources :feedbacks, only: %i[show]
  end
  get '/ptr/:id', to: 'ptr#show', as: 'ptr_lookup', constraints: { id: /[^\/]+/ }
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  mount MissionControl::Jobs::Engine, at: "/mission_control" if ENV["RAILS_ENV"] == "development"
end

app/models/mailbox.rb
# frozen_string_literal: true

require 'mail'

class Mailbox < ApplicationRecord
  encrypts :password

  validates :mail_address, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def fetch_reports
    retrieve_mails.each do |mail|
      next if mail.attachments.empty?

      mail.attachments.each do |attachment|
        feedback = Feedback.create(
          report: {
            io: StringIO.new(attachment.decoded),
            filename: attachment.filename
          }
        )
        ProcessReportJob.perform_later(feedback)
      end
    end
  end

  private

  def retrieve_mails
    imap = Mail::IMAP.new(
      {
        address: server,
        port:,
        user_name: mail_address,
        password:,
        enable_ssl: !disable_ssl_tls
      }
    )

    # TODO: Maybe it's better to store the mail localy once downloaded
    # and before analyzing them. In case of a crash or a bug
    imap.find_and_delete(what: :first, count: 10, order: :asc)
  end
end

app/controllers/mailboxes_controller.rb
# frozen_string_literal: true

class MailboxesController < AuthenticatedController
  before_action :set_mailbox, only: %i[show edit update destroy]

  # GET /mailboxes
  def index
    @mailboxes = Mailbox.all
  end

  # GET /mailboxes/1
  def show; end

  # GET /mailboxes/new
  def new
    @mailbox = Mailbox.new
  end

  # GET /mailboxes/1/edit
  def edit; end

  # POST /mailboxes
  def create
    @mailbox = Mailbox.new(mailbox_params)

    if @mailbox.save
      redirect_to @mailbox, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /mailboxes/1
  def update
    if @mailbox.update(mailbox_params)
      redirect_to @mailbox, notice: t('.success'), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /mailboxes/1
  def destroy
    @mailbox.destroy!
    redirect_to mailboxes_url, notice: t('.success'), status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_mailbox
    @mailbox = Mailbox.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def mailbox_params
    params.require(:mailbox).permit(:mail_address, :password, :server, :port, :verify_ssl, :disable_ssl_tls)
  end
end

app/helpers/mailboxes_helper.rb
# frozen_string_literal: true

module MailboxesHelper
end

app/views/mailboxes/_form.html.erb
<%= form_with(model: mailbox, class: 'contents') do |form| %>
  <% if mailbox.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(mailbox.errors.count, 'error') %> <%= t('.error_message') %>:</h2>
      <ul>
        <% mailbox.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :mail_address %>
    <%= form.text_field :mail_address, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
  </div>
  <div class="my-5">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
  </div>
  <div class="my-5">
    <%= form.label :server %>
    <%= form.text_field :server, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
  </div>
  <div class="my-5">
    <%= form.label :port %>
    <%= form.number_field :port, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
  </div>
  <div class="my-5">
    <%= form.label :verify_ssl %>
    <%= form.check_box :verify_ssl, class: 'block mt-2 h-5 w-5' %>
  </div>
  <div class="my-5">
    <%= form.label :disable_ssl_tls %>
    <%= form.check_box :disable_ssl_tls, class: 'block mt-2 h-5 w-5' %>
  </div>
  <div class="inline">
    <%= form.submit class: 'rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer' %>
  </div>
<% end %>

app/views/mailboxes/_mailbox.html.erb
<div id="<%= dom_id mailbox %>">
  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('.address') %>:</strong>
    <%= mailbox.mail_address %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('.server') %>:</strong>
    <%= mailbox.server %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('.port') %>:</strong>
    <%= mailbox.port %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('.verify_ssl') %>:</strong>
    <%= mailbox.verify_ssl %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('.disable_ssl_tls') %>:</strong>
    <%= mailbox.disable_ssl_tls %>
  </p>
  <% if action_name != "show" %>
    <%= link_to t('.link_show_mailbox'), mailbox, class: 'rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
    <%= link_to t('.link_edit_mailbox'), edit_mailbox_path(mailbox), class: 'rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium' %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/mailboxes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full pt-16">
  <h1 class="font-bold text-4xl"><%= t('.title') %></h1>
  <%= render 'form', mailbox: @mailbox %>
  <%= link_to t('.link_show_mailbox'), @mailbox, class: 'ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
  <%= link_to t('.link_back_to_mailboxes'), mailboxes_path, class: 'ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
</div>

app/views/mailboxes/index.html.erb
<div class="pt-16">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= t('.title') %></h1>
    <%= link_to t('.link_new_mailbox'), new_mailbox_path, class: 'rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium' %>
  </div>
  <div id="mailboxes" class="min-w-full">
    <%= render @mailboxes %>
  </div>
</div>

app/views/mailboxes/new.html.erb
<div class="mx-auto md:w-2/3 w-full pt-16">
  <h1 class="font-bold text-4xl"><%= t('.title') %></h1>
  <%= render 'form', mailbox: @mailbox %>
  <%= link_to t('.link_back_to_mailboxes'), mailboxes_path, class: 'ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
</div>

app/views/mailboxes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex pt-16">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%= render @mailbox %>
    <%= link_to t('.link_edit_mailbox'), edit_mailbox_path(@mailbox), class: 'mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
    <div class="inline-block ml-2">
      <%= button_to t('.link_destroy_mailbox'), mailbox_path(@mailbox), method: :delete, class: 'mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium' %>
    </div>
    <%= link_to t('.link_back_to_mailboxes'), mailboxes_path, class: 'ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
  </div>
</div>