config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :jobs, only: %i[index show]
  resources :feedback_uploads, only: %i[new create]
  resources :mailboxes
  resources :domains, only: %i[index show] do
    resources :feedbacks, only: %i[show]
  end
  get '/ptr/:id', to: 'ptr#show', as: 'ptr_lookup', constraints: { id: /[^\/]+/ }
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  mount MissionControl::Jobs::Engine, at: "/mission_control" if ENV["RAILS_ENV"] == "development"
end

app/models/feedback.rb
# frozen_string_literal: true

require 'zip'

class Feedback < ApplicationRecord
  before_create :add_random_report_id

  belongs_to :domain, optional: true
  belongs_to :organization, optional: true
  has_many :records, dependent: :destroy

  has_one_attached :report

  validates :report_id, uniqueness: { scope: :domain }

  def extract_report
    case report.filename.to_s
    when /.zip$/
      extract_from_zip_archive
    when /.xml$/
      extract_from_xml
    when /.gz$/
      extract_from_gzip_archive
    end
  end

  def extract_data
    extract_report_id
    extract_dates
    extract_organization
    extract_domain
    extract_policy_published
    extract_records

    return if Feedback.exists?(report_id:, domain:)

    save
  end

  def all_records_spf_valid?
    records.all? { |record| record.spf_result == 'pass' }
  end

  def any_records_spf_valid?
    records.any? { |record| record.spf_result == 'pass' }
  end

  def all_records_dkim_valid?
    records.all? { |record| record.dkim_result == 'pass' }
  end

  def any_records_dkim_valid?
    records.any? { |record| record.dkim_result == 'pass' }
  end

  def all_records_dmarc_valid?
    records.all?(&:dmarc)
  end

  def any_records_dmarc_valid?
    records.any?(&:dmarc)
  end

  private

  def add_random_report_id
    self.report_id = SecureRandom.alphanumeric(30) if report_id.nil?
  end

  def extract_report_id
    self.report_id = raw_content['feedback']['report_metadata']['report_id']
  end

  def extract_dates
    self.begin_date = Time.at(raw_content['feedback']['report_metadata']['date_range']['begin'].to_i).utc
    self.end_date = Time.at(raw_content['feedback']['report_metadata']['date_range']['end'].to_i).utc
  end

  def extract_organization
    self.organization = Organization.find_or_create_by(
      name: raw_content['feedback']['report_metadata']['org_name']
    )
  end

  def extract_domain
    self.domain = Domain.find_or_create_by(
      name: raw_content['feedback']['policy_published']['domain']
    )
  end

  def extract_policy_published
    self.policy_published = raw_content['feedback']['policy_published']
  end

  def extract_records
    return if raw_content.dig('feedback', 'record').empty?

    if raw_content['feedback']['record'].instance_of?(Hash)
      record = records.new
      record.update_from_hash(raw_content['feedback']['record'])
    elsif raw_content['feedback']['record'].instance_of?(Array)
      raw_content['feedback']['record'].each do |raw_record|
        record = records.new
        record.update_from_hash(raw_record)
      end
    end
  end

  def extract_from_zip_archive
    Zip::File.open_buffer(report.download) do |zip|
      zip.each do |entry|
        next unless entry.name.match?(/.xml$/)

        self.raw_content = JSON.parse(Crack::XML.parse(entry.get_input_stream.read).to_json)
        save

        return true
      end
    end
  end

  def extract_from_gzip_archive
    report.open do |r|
      gz_file = Zlib::GzipReader.new(r)

      self.raw_content = JSON.parse(Crack::XML.parse(gz_file.read).to_json)
      save
    end
  end

  def extract_from_xml
    self.raw_content = JSON.parse(Crack::XML.parse(report.download).to_json)

    save
  end
end

app/controllers/feedbacks_controller.rb
# frozen_string_literal: true

class FeedbacksController < AuthenticatedController
  before_action :set_feedback, only: %i[show]

  # Get /domains/1/feedbacks/1
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_feedback
    @feedback = Feedback.includes(:domain, :records).find(params[:id])
  end
end

app/helpers/feedbacks_helper.rb
# frozen_string_literal: true

module FeedbacksHelper
  def source_ip_list(feedback)
    records = feedback.records
    record_count = records.length

    return records.first.source_ip if record_count == 1

    "#{records.first.source_ip} + #{record_count - 1} others IP"
  end
end

app/views/feedbacks/_organization.html.erb
<div class="space-y-16 py-16 xl:space-y-20">
  <div class="mt-6 overflow-hidden border-t border-gray-100 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8  dark:bg-slate-800 dark:border-gray-400">
    <div class="px-4 py-10 sm:px-6 lg:px-8">
      <div class="mx-auto flex items-center justify-between gap-x-8 lg:mx-0">
        <div class="flex items-center gap-x-6">
          <img src="https://tailwindui.com/img/logos/48x48/tuple.svg" alt="" class="h-16 w-16 flex-none rounded-full ring-1 ring-gray-900/10">
          <h1>
            <div class="text-sm leading-6 text-gray-500 dark:text-gray-200"><%= t('.report_id') %> <span class="text-gray-700 dark:text-gray-400"><%= feedback.report_id %></span></div>
            <div class="mt-1 text-base font-semibold leading-6 text-gray-900 dark:text-gray-950 dark:font-bold"><%= organization.name %></div>
          </h1>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/feedbacks/_record.html.erb
<tr>
  <td class="whitespace-nowrap py-5 pl-4 pr-3 text-sm sm:pl-0">
    <div class="flex items-center">
      <div class="ml-4">
        <div class="font-medium text-gray-900 dark:font-bold">
          <%= turbo_frame_tag "dns_#{record.source_ip}", src: ptr_lookup_path(record.source_ip), lazy: true do %>
            <%= t('.dns_placeholder') %>
          <% end %>
        </div>
        <div class="mt-1 text-gray-500 dark:text-gray-400"><%= record.source_ip %></div>
      </div>
    </div>
  </td>
  <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
    <%= render partial: 'feedbacks/result_badge', locals: { pass: record.dmarc } %>
  </td>
  <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
    <%= render partial: 'feedbacks/result_badge', locals: { pass: record.dkim_pass } %>
  </td>
  <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
    <%= render partial: 'feedbacks/result_badge', locals: { pass: record.spf_pass } %>
  </td>
  <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500 dark:text-gray-400"><%= record.count %></td>
</tr>

app/views/feedbacks/_records.html.erb
<div class="px-4 sm:px-6 lg:px-8 space-y-16 py-16 xl:space-y-20">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900 dark:text-gray-300"><%= t('.title') %></h1>
      <p class="mt-2 text-sm text-gray-700 dark:text-gray-500"><%= t('.description') %></p>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 dark:text-gray-300 sm:pl-0"><%= t('.table_head_source') %></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-gray-300"><%= t('.table_head_dmarc_status') %></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-gray-300"><%= t('.table_head_dkim_status') %></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-gray-300"><%= t('.table_head_spf_status') %></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-gray-300"><%= t('.table_head_volume') %></th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white dark:bg-slate-800">
            <% records.each do |record| %>
              <%= render partial: 'feedbacks/record', locals: { record: } %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/feedbacks/_result_badge.html.erb
<% if pass %>
  <span class="inline-flex items-center rounded-md bg-green-50 dark:bg-green-500 px-2 py-1 text-xs font-medium text-green-700 dark:text-gray-900 ring-1 ring-inset ring-green-600/20"><%= t('.pass') %></span>
<% else %>
  <span class="inline-flex items-center rounded-md bg-red-50 dark:bg-red-400 px-2 py-1 text-xs font-medium text-red-700 dark:text-gray-900 ring-1 ring-inset ring-red-600/20"><%= t('.fail') %></span>
<% end %>

app/views/feedbacks/show.html.erb
<div id="<%= dom_id @feedback %>" class="relative isolate overflow-hidden pt-16 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <%= render partial: 'feedbacks/organization', locals: { organization: @feedback.organization, feedback: @feedback } %>
  <%= render partial: 'feedbacks/records', locals: { records: @feedback.records } %>
</div>